### ISSUE TITLE
How to use IP-Passthrough？

### ISSUE THREAD

**Issue by yuanjie1590** [NextBlaubeere/bridge-mode-openWRT-LEDE#1]
Hi!
plase tell me how to use IP-Passthrough?  thanks!

**Comment by NextBlaubeere** [comment]
hey, it is descripted here (german only):
https://www.lteforum.at/mobilfunk/cat-6-module-basteleien.4969/seite-154.html#post-116365

you will need some programming- and linux-knowHow.
If you haven't it won't work. ;-)

**Comment by yuanjie1590** [comment]
Hi！
thank you very much first！
Use your method, I did not achieve the function, can help me find out where the problem?
My platform is openwrt
Here is my configuration file,
root@Router:/# cat /etc/config/network 

config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'
        option ip_int_instance '1'

config globals 'globals'
        option ula_prefix 'fd43:fc2a:ed3b::/48'

config interface 'lan'
        option ifname 'eth0'
        option proto 'static'
        option ipaddr '192.168.11.1'
        option netmask '255.255.255.0'
        option delegate '0'
        option ip_int_instance '5'

config interface 'wan'
        option ifname 'eth1'
        option proto 'dhcp'
        option ip_int_instance '3'

config interface 'wan6'
        option ifname 'eth1'
        option proto 'dhcpv6'

config interface '4G'
        option ifname 'wwan0'
        option proto 'dhcp'
        option ip_int_instance '4'

root@Router:/# cat /etc/config/dhcp 

config dnsmasq
        option domainneeded '1'
        option boguspriv '1'
        option filterwin2k '0'
        option localise_queries '1'
        option rebind_protection '1'
        option rebind_localhost '1'
        option local '/lan/'
        option domain 'lan'
        option expandhosts '1'
        option nonegcache '0'
        option authoritative '1'
        option readethers '1'
        option leasefile '/tmp/dhcp.leases'
        option resolvfile '/tmp/resolv.conf.auto'
        option localservice '1'

config dhcp 'lan'
        option interface 'lan'
        option leasetime '2m'
        option ra 'server'
        option ra_management '1'
        option bridge_mode '1'
        option bridge_interface 'wan'
        option dhcp_pool_instance '3'

config dhcp 'wan'
        option interface 'wan'
        option ignore '1'
        option dhcp_pool_instance '2'

config odhcpd 'odhcpd'
        option maindhcp '0'
        option leasefile '/tmp/hosts/odhcpd'
        option leasetrigger '/usr/sbin/odhcpd-update'

I think we should do in the /etc/dnsmasq.config point configuration, but do not know what should be configured specifically!

**Comment by NextBlaubeere** [comment]
Have you already compiled my modified dnsmasq for your device?
That is the first thing you have to do. ;)

**Comment by yuanjie1590** [comment]
Hi!
 I fix this problem!  Openwrt is missing a dnsmasq user!
thanks!

**Comment by NextBlaubeere** [comment]
Ok? I don't know nothing about that.

I know that the original dnsmasq has restrections to give out addresses of another network, which is needed in this implementation of a bridge mode. So i modified it to allow that.
You have to compile the code for your device and replace the original dnsmasq with it in the first place.

**Comment by yuanjie1590** [comment]
yes, I replaced with your dnsmasq.

**Comment by yuanjie1590** [comment]
There is a small problem, I can only visit the gateway, LAN can not visit the other pc? Need to modify parameters?

**Comment by NextBlaubeere** [comment]
i don't know the network, i don't know where the "other pc" is... you have to go in more detail. (much more!)
bridge-mode means assigning the ip you would normaly get from WAN to a device on LAN. Of course you can not run multiple devices in lan.

**Comment by yuanjie1590** [comment]
I can get IP via bridge mode, but I can not access the network！  I can Ping 192.168.2.1 ，but can not ping 192.168.2.81！

               router_1 :192.168.2.1
                /                   \
              /                       \
openwrt 192.168.2.85               pc_1 192.168.2.81
            |
            |
       (bridge mode)
            |
            |
     pc_2 192.168.2.85

**Comment by yuanjie1590** [comment]
I can get IP via bridge mode, but I can not access the network！ I can Ping 192.168.2.1 ，but can not ping 192.168.2.81！

           router_1 :192.168.2.1
            /                   \
          /                       \
openwrt 192.168.2.85           pc_1 192.168.2.81
    |
    |
(bridge mode)
    |
    |
pc_2 192.168.2.85

**Comment by yuanjie1590** [comment]
I can get IP via bridge mode, but I can not access the network！ on pc_2 I can Ping 192.168.2.1 ，but can not ping 192.168.2.81！

           router_1 :192.168.2.1
            /                   \
          /                       \
          openwrt 192.168.2.85           pc_1 192.168.2.81
          |
          |
          (bridge mode)
          |
          |
          pc_2 192.168.2.85

**Comment by NextBlaubeere** [comment]
A) Is it possible without the openwrt-device?
B) Check your Firewall-Settings (on the openwrt and PCs). Set everything to "allow" for test purposes.
C) show the output of "ip route" and "ip rule"

**Comment by yuanjie1590** [comment]
bridge-mode is runing openwrt (192.168.2.85)!

root@Router:/# ip route
default via 192.168.2.1 dev eth1  proto static  src 192.168.2.85 
192.168.2.0/24 dev eth0  proto kernel  scope link  src 192.168.2.1 
192.168.2.1 dev eth1  proto static  scope link  src 192.168.2.85 
192.168.8.0/24 dev eth0  proto kernel  scope link  src 192.168.8.138 

root@Router:/# ip rule
0:      from all lookup 128 
1:      from all lookup local 
142:    from all iif eth0 lookup 42 
143:    from all iif eth1 lookup 43 
2253:   from all fwmark 0xfd00/0xff00 blackhole
2254:   from all fwmark 0xfe00/0xff00 unreachable
32766:  from all lookup main 
32767:  from all lookup default 


Note: eth0 is Lan and eth1 is Wan!

**Comment by NextBlaubeere** [comment]
looks good, check your firewall!

**Comment by yuanjie1590** [comment]
root@Router:/# cat /etc/config/firewall 

config defaults
        option syn_flood '1'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'

config zone
        option name 'lan'
        list network 'lan'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'

config zone
        option name 'wan'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'
        option masq '1'
        option mtu_fix '1'
        option network 'wan wan6 3G 4G'

config forwarding
        option src 'lan'
        option dest 'wan'

config rule
        option name 'Allow-DHCP-Renew'
        option src 'wan'
        option proto 'udp'
        option dest_port '68'
        option target 'ACCEPT'
        option family 'ipv4'

config rule
        option name 'Allow-Ping'
        option src 'wan'
        option proto 'icmp'
        option icmp_type 'echo-request'
        option family 'ipv4'
        option target 'ACCEPT'

config rule
        option name 'Allow-IGMP'
        option src 'wan'
        option proto 'igmp'
        option family 'ipv4'
        option target 'ACCEPT'

config rule
        option name 'Allow-DHCPv6'
        option src 'wan'
        option proto 'udp'
        option src_ip 'fe80::/10'
        option src_port '547'
        option dest_ip 'fe80::/10'
        option dest_port '546'
        option family 'ipv6'
        option target 'ACCEPT'

config rule
        option name 'Allow-MLD'
        option src 'wan'
        option proto 'icmp'
        option src_ip 'fe80::/10'
        list icmp_type '130/0'
        list icmp_type '131/0'
        list icmp_type '132/0'
        list icmp_type '143/0'
        option family 'ipv6'
        option target 'ACCEPT'

config rule
        option name 'Allow-ICMPv6-Input'
        option src 'wan'
        option proto 'icmp'
        list icmp_type 'echo-request'
        list icmp_type 'echo-reply'
        list icmp_type 'destination-unreachable'
        list icmp_type 'packet-too-big'
        list icmp_type 'time-exceeded'
        list icmp_type 'bad-header'
        list icmp_type 'unknown-header-type'
        list icmp_type 'router-solicitation'
        list icmp_type 'neighbour-solicitation'
        list icmp_type 'router-advertisement'
        list icmp_type 'neighbour-advertisement'
        option limit '1000/sec'
        option family 'ipv6'
        option target 'ACCEPT'

config rule
        option name 'Allow-ICMPv6-Forward'
        option src 'wan'
        option dest '*'
        option proto 'icmp'
        list icmp_type 'echo-request'
        list icmp_type 'echo-reply'
        list icmp_type 'destination-unreachable'
        list icmp_type 'packet-too-big'
        list icmp_type 'time-exceeded'
        list icmp_type 'bad-header'
        list icmp_type 'unknown-header-type'
        option limit '1000/sec'
        option family 'ipv6'
        option target 'ACCEPT'

config include
        option path '/etc/firewall.user'

config rule
        option src 'wan'
        option dest 'lan'
        option proto 'esp'
        option target 'ACCEPT'

config rule
        option src 'wan'
        option dest 'lan'
        option dest_port '500'
        option proto 'udp'
        option target 'ACCEPT'

config rule
        option target 'ACCEPT'
        option src 'wan'
        option proto 'tcp'
        option dest_port '22'
        option name 'SSH'

config rule
        option target 'ACCEPT'
        option src 'wan'
        option proto 'tcp'
        option dest_port '80'
        option name 'WEB'

config include 'ipsec'
        option type 'script'
        option path '/etc/ipsec.d/firewall.include'
        option family 'IPv4'

config include 'miniupnpd'
        option type 'script'
        option path '/usr/share/miniupnpd/firewall.include'
        option family 'any'
        option reload '1'

**Comment by NextBlaubeere** [comment]
Ah right, this bridge mode is designed to forward EVERY traffic to the gateway. So no other devices than gateway and your device on the same network are allowed.

I don't know what you want to achieve but this Bridge-Mode is meant for running a Home-Router with Public-IP with your ISPs modem. I fear it might not fit for your situation.

**Comment by yuanjie1590** [comment]
My needs like you!
now, I got IP 118.114.168.208 via pppoe. but pc_2 can not get this IP. why?
             ISP
              /                   
             /
openwrt pppoe 118.114.168.208               
            |
            |
       (bridge mode)
            |
            |
         pc_2

this is log for dnsmasq!

Wed Aug 23 16:24:43 2017 daemon.info dnsmasq[18706]: Attention: This is a custom build for Blaubeere BridgeMode
Wed Aug 23 16:24:43 2017 daemon.info dnsmasq[18706]: started, version 2.76 cachesize 150
Wed Aug 23 16:24:43 2017 daemon.info dnsmasq[18706]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
Wed Aug 23 16:24:43 2017 daemon.info dnsmasq[18706]: DNS service limited to local subnets
Wed Aug 23 16:24:43 2017 daemon.info dnsmasq[18706]: using local addresses only for domain lan
Wed Aug 23 16:24:43 2017 daemon.info dnsmasq[18706]: reading /tmp/resolv.conf.auto
Wed Aug 23 16:24:43 2017 daemon.info dnsmasq[18706]: using local addresses only for domain lan
Wed Aug 23 16:24:43 2017 daemon.info dnsmasq[18706]: using nameserver 61.139.2.69#53
Wed Aug 23 16:24:43 2017 daemon.info dnsmasq[18706]: using nameserver 218.6.200.139#53
Wed Aug 23 16:24:43 2017 daemon.info dnsmasq[18706]: read /etc/hosts - 1 addresses
Wed Aug 23 16:24:43 2017 daemon.info dnsmasq[18706]: read /tmp/hosts/dhcp.cfg02411c - 1 addresses

Probably the problem lies here：
DNS service limited to local subnets

# ifconfig
pppoe-wan Link encap:Point-to-Point Protocol  
          inet addr:118.114.168.208  P-t-P:118.114.168.1  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1492  Metric:1
          RX packets:1027 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1076 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3 
          RX bytes:117874 (115.1 KiB)  TX bytes:139779 (136.5 KiB)

**Comment by NextBlaubeere** [comment]
i thought this is already working? doesn't seem pc makes a dhcp-request.

no need for dns, so no the problem is not here.

**Comment by yuanjie1590** [comment]
I find this "no address range available for DHCP request via eth0".
the problem is here?

Wed Aug 23 19:35:49 2017 daemon.info dnsmasq[7274]: Attention: This is a custom build for Blaubeere BridgeMode
Wed Aug 23 19:35:49 2017 daemon.info dnsmasq[7274]: started, version 2.76 cachesize 150
Wed Aug 23 19:35:49 2017 daemon.info dnsmasq[7274]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
Wed Aug 23 19:35:49 2017 daemon.info dnsmasq-dhcp[7274]: DHCP, IP range 118.114.168.208 -- 118.114.168.208, lease time 8h
Wed Aug 23 19:35:49 2017 daemon.info dnsmasq[7274]: using local addresses only for domain lan
Wed Aug 23 19:35:49 2017 daemon.info dnsmasq[7274]: reading /tmp/resolv.conf.auto
Wed Aug 23 19:35:49 2017 daemon.info dnsmasq[7274]: using local addresses only for domain lan
Wed Aug 23 19:35:49 2017 daemon.info dnsmasq[7274]: using nameserver 61.139.2.69#53
Wed Aug 23 19:35:49 2017 daemon.info dnsmasq[7274]: using nameserver 218.6.200.139#53
Wed Aug 23 19:35:49 2017 daemon.info dnsmasq[7274]: read /etc/hosts - 1 addresses
Wed Aug 23 19:35:49 2017 daemon.info dnsmasq[7274]: read /tmp/hosts/dhcp.cfg02411c - 1 addresses
Wed Aug 23 19:35:49 2017 daemon.info dnsmasq-dhcp[7274]: read /etc/ethers - 0 addresses
Wed Aug 23 19:35:49 2017 daemon.warn dnsmasq-dhcp[7274]: no address range available for DHCP request via eth0
Wed Aug 23 19:35:56 2017 daemon.warn dnsmasq-dhcp[7274]: no address range available for DHCP request via eth0
Wed Aug 23 19:36:12 2017 daemon.warn dnsmasq-dhcp[7274]: no address range available for DHCP request via eth0
Wed Aug 23 19:36:32 2017 daemon.warn dnsmasq-dhcp[7274]: no address range available for DHCP request via eth0
Wed Aug 23 19:36:40 2017 daemon.warn dnsmasq-dhcp[7274]: no address range available for DHCP request via eth0
Wed Aug 23 19:36:57 2017 daemon.warn dnsmasq-dhcp[7274]: no address range available for DHCP request via eth0
root@Router:/#

**Comment by NextBlaubeere** [comment]
Yes, maybe the address is already taken by another client, i don't know.
Maybe try to set the lease time to the lowest possible value (2m) for test purposes.

**Comment by yuanjie1590** [comment]
Hi:
Tell you a good news！
Bridge mode is working!
My 4g module was previously in ppp mode, now changed to NDIS mode! and stop firewall!
It can work properly!
If work in ppp mode, need to change where? thanks！

**Comment by NextBlaubeere** [comment]
I don't know why it won't run in ppp mode. I am running it in mbim mode myself.
Bug nice to hear its workign now! :-)
